# Generated by Django 5.2.7 on 2025-11-20 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto_Vehiculos', '0020_remove_cliente_creado_remove_cliente_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='precio',
            field=models.CharField(max_length=100),
        ),
    ]
